name = "crypto-signal-scheduler"
main = "src/index.js"
compatibility_date = "2025-01-01"

[durable_objects]
bindings = [
  { name = "CLOSE_SCHEDULER", class_name = "CloseScheduler" },
  { name = "AUTOPILOT", class_name = "Autopilot" },
  { name = "USERS", class_name = "Users" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CloseScheduler"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Autopilot"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["Users"]
